<?php

namespace D0ggy\LaraSlimUrl\Tests;

use D0ggy\LaraSlimUrl\Models\SlimUrl;
use D0ggy\LaraSlimUrl\SlimUrlServiceProvider;
use Illuminate\Contracts\Config\Repository;

class TestCase extends \Orchestra\Testbench\TestCase
{
    protected $loadEnvironmentVariables = true;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withFactories(__DIR__.'/../database/factories');
    }

    protected function getPackageProviders($app): array
    {
        return [
            SlimUrlServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        $config = $app->make(Repository::class);
        // $config->set('auth.defaults.provider', 'users');

        // perform environment setup
        $app['config']->set('database.default', 'mysql');

        $app['config']->set('database.connections.mysql', [
            'driver'      => 'mysql',
            'url'         => env('DATABASE_URL'),
            'host'        => env('DB_HOST', '127.0.0.1'),
            'port'        => env('DB_PORT', '3306'),
            'database'    => env('DB_DATABASE', 'lb_test'),
            'username'    => env('DB_USERNAME', 'homestead'),
            'password'    => env('DB_PASSWORD', 'secret'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset'     => 'utf8mb4',
            'collation'   => 'utf8mb4_unicode_ci',
        ]);

        $app['config']->set('slim_url.database.model', SlimUrl::class);
        $app['config']->set('slim_url.database.table', 'slim_urls');
        $app['config']->set('slim_url.route.raw_string', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789');
    }
}
