<?php

namespace D0ggy\LaraSlimUrl\Tests\Unit;

use D0ggy\LaraSlimUrl\Models\SlimUrl;
use D0ggy\LaraSlimUrl\Tests\TestCase;
use Faker\Generator as Faker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class SlimUrlTest extends TestCase
{
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        // import the CreateSlimUrlsTable class from the migration
        include_once __DIR__ . '/../../database/migrations/create_slim_urls_table.php.stub';

        // run the up() method of that migration class
        (new \CreateSlimUrlsTable())->up();
    }

    /**
     * @test
     */
    function a_slim_url_has_a_short_url()
    {
        $longUrl  = 'http://www.emard.org/harum-laborum-omnis-molestias-qui-tempora-iusto-est-maxime';
        $slim_url = \D0ggy\LaraSlimUrl\Facades\SlimUrl::generateSlimUrl($longUrl, false);

        $more_slim_url = \D0ggy\LaraSlimUrl\Facades\SlimUrl::generateSlimUrl($longUrl, false);

        $this->assertInstanceOf(SlimUrl::class, $slim_url);
        $this->assertInstanceOf(SlimUrl::class, $more_slim_url);
        $this->assertEquals($slim_url->slim_url, $more_slim_url->slim_url);

    }
}